// <auto-generated />
using System;
using AniCharades.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AniCharades.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190324202155_CreateRelationStrategyCriteria")]
    partial class CreateRelationStrategyCriteria
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085");

            modelBuilder.Entity("AniCharades.Data.Models.AnimeEntry", b =>
                {
                    b.Property<long>("MalId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("SeriesId");

                    b.HasKey("MalId");

                    b.HasIndex("SeriesId");

                    b.ToTable("Animes");
                });

            modelBuilder.Entity("AniCharades.Data.Models.MangaEntry", b =>
                {
                    b.Property<long>("MalId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("SeriesId");

                    b.HasKey("MalId");

                    b.HasIndex("SeriesId");

                    b.ToTable("Mangas");
                });

            modelBuilder.Entity("AniCharades.Data.Models.RelationStrategyCriteria", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Keywords");

                    b.Property<int>("KeywordsMatch");

                    b.Property<string>("Relations");

                    b.Property<string>("Strategy");

                    b.HasKey("Id");

                    b.ToTable("RelationStrategyCriterias");
                });

            modelBuilder.Entity("AniCharades.Data.Models.SeriesEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ImageUrl");

                    b.Property<string>("Title");

                    b.Property<string>("Translations");

                    b.HasKey("Id");

                    b.ToTable("Series");
                });

            modelBuilder.Entity("AniCharades.Data.Models.AnimeEntry", b =>
                {
                    b.HasOne("AniCharades.Data.Models.SeriesEntry", "Series")
                        .WithMany("AnimePositions")
                        .HasForeignKey("SeriesId");
                });

            modelBuilder.Entity("AniCharades.Data.Models.MangaEntry", b =>
                {
                    b.HasOne("AniCharades.Data.Models.SeriesEntry", "Series")
                        .WithMany("MangaPositions")
                        .HasForeignKey("SeriesId");
                });
#pragma warning restore 612, 618
        }
    }
}
